# Generated by Django 6.0 on 2026-02-12 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersolvedproblem',
            unique_together=set(),
        ),
    ]
