# Generated by Django 5.2.11 on 2026-02-20 08:04
# [2026-02-20] 버그헌트 데이터에 title 필드 추가

from django.db import migrations


def update_bughunt_titles(apps, schema_editor):
    """
    1. PracticeDetail의 content_data에 title 추가
    2. UserSolvedProblem의 submitted_data에 title 추가
    """
    PracticeDetail = apps.get_model('core', 'PracticeDetail')
    UserSolvedProblem = apps.get_model('core', 'UserSolvedProblem')

    # progressive-problems.json의 id → title 매핑
    PROBLEM_TITLES = {
        'S1': 'Python 기초 버그 수정',
        'S2': 'QA 티켓 해결하기',
        'S3': '코드 리뷰 버그 수정',
        'S4': 'PyTorch 학습 루프 디버깅',
        'S5': '데이터 파이프라인 최적화',
        'S6': '모델 저장/로드 문제 해결',
        'S7': 'Transformer 모델 Fine-tuning',
    }

    updated_practice_details = 0
    updated_user_solved = 0

    # 1. PracticeDetail의 content_data에 title 추가
    for detail in PracticeDetail.objects.filter(practice_id='unit02'):
        if detail.content_data and isinstance(detail.content_data, dict):
            problem_id = detail.content_data.get('id')
            if problem_id in PROBLEM_TITLES and 'title' not in detail.content_data:
                detail.content_data['title'] = PROBLEM_TITLES[problem_id]
                detail.save()
                updated_practice_details += 1

    # 2. UserSolvedProblem의 submitted_data에 title 추가
    for detail in PracticeDetail.objects.filter(practice_id='unit02'):
        # PracticeDetail의 content_data에서 title 가져오기
        title = None
        if detail.content_data and isinstance(detail.content_data, dict):
            title = detail.content_data.get('title')

        if title:
            # 해당 PracticeDetail의 모든 제출 기록 업데이트
            solved_problems = UserSolvedProblem.objects.filter(practice_detail=detail)
            for solved in solved_problems:
                if isinstance(solved.submitted_data, dict) and 'title' not in solved.submitted_data:
                    solved.submitted_data['title'] = title
                    solved.save()
                    updated_user_solved += 1

    print(f'[Migration] PracticeDetail 업데이트: {updated_practice_details}개')
    print(f'[Migration] UserSolvedProblem 업데이트: {updated_user_solved}개')


def reverse_update(apps, schema_editor):
    """
    롤백 시 title 필드 제거 (선택사항)
    """
    pass  # title 필드를 제거하지 않고 유지


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_usersolvedproblem_unique_together'),
    ]

    operations = [
        migrations.RunPython(update_bughunt_titles, reverse_update),
    ]
