# Generated by Django 5.2.10 on 2026-01-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_common_userdetail_delete_sample_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='interests',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='job_role',
            field=models.TextField(blank=True, null=True),
        ),
    ]
