# Generated by Django 5.2.11 on 2026-02-23 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_update_bughunt_data_with_titles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='common',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, help_text='생성 일시'),
        ),
        migrations.AlterField(
            model_name='common',
            name='create_id',
            field=models.CharField(blank=True, help_text='생성자 ID', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='common',
            name='update_date',
            field=models.DateTimeField(auto_now=True, help_text='수정 일시'),
        ),
        migrations.AlterField(
            model_name='common',
            name='update_id',
            field=models.CharField(blank=True, help_text='수정자 ID', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='common',
            name='use_yn',
            field=models.CharField(default='Y', help_text='사용 여부 (Y/N)', max_length=1),
        ),
        migrations.AlterField(
            model_name='dashboardlog',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, help_text='생성 일시'),
        ),
        migrations.AlterField(
            model_name='dashboardlog',
            name='create_id',
            field=models.CharField(blank=True, help_text='생성자 ID', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardlog',
            name='update_date',
            field=models.DateTimeField(auto_now=True, help_text='수정 일시'),
        ),
        migrations.AlterField(
            model_name='dashboardlog',
            name='update_id',
            field=models.CharField(blank=True, help_text='수정자 ID', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardlog',
            name='use_yn',
            field=models.CharField(default='Y', help_text='사용 여부 (Y/N)', max_length=1),
        ),
        migrations.AlterField(
            model_name='practice',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, help_text='생성 일시'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='create_id',
            field=models.CharField(blank=True, help_text='생성자 ID', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='practice',
            name='update_date',
            field=models.DateTimeField(auto_now=True, help_text='수정 일시'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='update_id',
            field=models.CharField(blank=True, help_text='수정자 ID', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='practice',
            name='use_yn',
            field=models.CharField(default='Y', help_text='사용 여부 (Y/N)', max_length=1),
        ),
        migrations.AlterField(
            model_name='practicedetail',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, help_text='생성 일시'),
        ),
        migrations.AlterField(
            model_name='practicedetail',
            name='create_id',
            field=models.CharField(blank=True, help_text='생성자 ID', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='practicedetail',
            name='update_date',
            field=models.DateTimeField(auto_now=True, help_text='수정 일시'),
        ),
        migrations.AlterField(
            model_name='practicedetail',
            name='update_id',
            field=models.CharField(blank=True, help_text='수정자 ID', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='practicedetail',
            name='use_yn',
            field=models.CharField(default='Y', help_text='사용 여부 (Y/N)', max_length=1),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, help_text='생성 일시'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='create_id',
            field=models.CharField(blank=True, help_text='생성자 ID', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='update_date',
            field=models.DateTimeField(auto_now=True, help_text='수정 일시'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='update_id',
            field=models.CharField(blank=True, help_text='수정자 ID', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='use_yn',
            field=models.CharField(default='Y', help_text='사용 여부 (Y/N)', max_length=1),
        ),
        migrations.AlterField(
            model_name='useravatar',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, help_text='생성 일시'),
        ),
        migrations.AlterField(
            model_name='useravatar',
            name='create_id',
            field=models.CharField(blank=True, help_text='생성자 ID', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='useravatar',
            name='update_date',
            field=models.DateTimeField(auto_now=True, help_text='수정 일시'),
        ),
        migrations.AlterField(
            model_name='useravatar',
            name='update_id',
            field=models.CharField(blank=True, help_text='수정자 ID', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='useravatar',
            name='use_yn',
            field=models.CharField(default='Y', help_text='사용 여부 (Y/N)', max_length=1),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, help_text='생성 일시'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='create_id',
            field=models.CharField(blank=True, help_text='생성자 ID', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='update_date',
            field=models.DateTimeField(auto_now=True, help_text='수정 일시'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='update_id',
            field=models.CharField(blank=True, help_text='수정자 ID', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='use_yn',
            field=models.CharField(default='Y', help_text='사용 여부 (Y/N)', max_length=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, help_text='생성 일시'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='create_id',
            field=models.CharField(blank=True, help_text='생성자 ID', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='update_date',
            field=models.DateTimeField(auto_now=True, help_text='수정 일시'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='update_id',
            field=models.CharField(blank=True, help_text='수정자 ID', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='use_yn',
            field=models.CharField(default='Y', help_text='사용 여부 (Y/N)', max_length=1),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, help_text='생성 일시'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='create_id',
            field=models.CharField(blank=True, help_text='생성자 ID', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='update_date',
            field=models.DateTimeField(auto_now=True, help_text='수정 일시'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='update_id',
            field=models.CharField(blank=True, help_text='수정자 ID', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='use_yn',
            field=models.CharField(default='Y', help_text='사용 여부 (Y/N)', max_length=1),
        ),
        migrations.AlterField(
            model_name='usersolvedproblem',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, help_text='생성 일시'),
        ),
        migrations.AlterField(
            model_name='usersolvedproblem',
            name='create_id',
            field=models.CharField(blank=True, help_text='생성자 ID', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usersolvedproblem',
            name='update_date',
            field=models.DateTimeField(auto_now=True, help_text='수정 일시'),
        ),
        migrations.AlterField(
            model_name='usersolvedproblem',
            name='update_id',
            field=models.CharField(blank=True, help_text='수정자 ID', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usersolvedproblem',
            name='use_yn',
            field=models.CharField(default='Y', help_text='사용 여부 (Y/N)', max_length=1),
        ),
    ]
