# Generated by Django 6.0.2 on 2026-02-21 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_update_bughunt_data_with_titles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='common',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, help_text='생성 일시'),
        ),
        migrations.AlterField(
            model_name='common',
            name='create_id',
            field=models.CharField(blank=True, help_text='생성자 ID', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='common',
            name='update_date',
            field=models.DateTimeField(auto_now=True, help_text='수정 일시'),
        ),
        migrations.AlterField(
            model_name='common',
            name='update_id',
            field=models.CharField(blank=True, help_text='수정자 ID', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='common',
            name='use_yn',
            field=models.CharField(default='Y', help_text='사용 여부 (Y/N)', max_length=1),
        ),
        migrations.AlterField(
            model_name='dashboardlog',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, help_text='생성 일시'),
        ),
        migrations.AlterField(
            model_name='dashboardlog',
            name='create_id',
            field=models.CharField(blank=True, help_text='생성자 ID', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardlog',
            name='update_date',
            field=models.DateTimeField(auto_now=True, help_text='수정 일시'),
        ),
        migrations.AlterField(
            model_name='dashboardlog',
            name='update_id',
            field=models.CharField(blank=True, help_text='수정자 ID', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardlog',
            name='use_yn',
            field=models.CharField(default='Y', help_text='사용 여부 (Y/N)', max_length=1),
        ),
        migrations.AlterField(
            model_name='practice',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, help_text='생성 일시'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='create_id',
            field=models.CharField(blank=True, help_text='생성자 ID', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='practice',
            name='update_date',
            field=models.DateTimeField(auto_now=True, help_text='수정 일시'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='update_id',
            field=models.CharField(blank=True, help_text='수정자 ID', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='practice',
            name='use_yn',
            field=models.CharField(default='Y', help_text='사용 여부 (Y/N)', max_length=1),
        ),
        migrations.AlterField(
            model_name='practicedetail',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, help_text='생성 일시'),
        ),
        migrations.AlterField(
            model_name='practicedetail',
            name='create_id',
            field=models.CharField(blank=True, help_text='생성자 ID', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='practicedetail',
            name='update_date',
            field=models.DateTimeField(auto_now=True, help_text='수정 일시'),
        ),
        migrations.AlterField(
            model_name='practicedetail',
            name='update_id',
            field=models.CharField(blank=True, help_text='수정자 ID', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='practicedetail',
            name='use_yn',
            field=models.CharField(default='Y', help_text='사용 여부 (Y/N)', max_length=1),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, help_text='생성 일시'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='create_id',
            field=models.CharField(blank=True, help_text='생성자 ID', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='update_date',
            field=models.DateTimeField(auto_now=True, help_text='수정 일시'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='update_id',
            field=models.CharField(blank=True, help_text='수정자 ID', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='use_yn',
            field=models.CharField(default='Y', help_text='사용 여부 (Y/N)', max_length=1),
        ),
        migrations.AlterField(
            model_name='useravatar',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, help_text='생성 일시'),
        ),
        migrations.AlterField(
            model_name='useravatar',
            name='create_id',
            field=models.CharField(blank=True, help_text='생성자 ID', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='useravatar',
            name='update_date',
            field=models.DateTimeField(auto_now=True, help_text='수정 일시'),
        ),
        migrations.AlterField(
            model_name='useravatar',
            name='update_id',
            field=models.CharField(blank=True, help_text='수정자 ID', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='useravatar',
            name='use_yn',
            field=models.CharField(default='Y', help_text='사용 여부 (Y/N)', max_length=1),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, help_text='생성 일시'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='create_id',
            field=models.CharField(blank=True, help_text='생성자 ID', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='update_date',
            field=models.DateTimeField(auto_now=True, help_text='수정 일시'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='update_id',
            field=models.CharField(blank=True, help_text='수정자 ID', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='use_yn',
            field=models.CharField(default='Y', help_text='사용 여부 (Y/N)', max_length=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, help_text='생성 일시'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='create_id',
            field=models.CharField(blank=True, help_text='생성자 ID', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='update_date',
            field=models.DateTimeField(auto_now=True, help_text='수정 일시'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='update_id',
            field=models.CharField(blank=True, help_text='수정자 ID', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='use_yn',
            field=models.CharField(default='Y', help_text='사용 여부 (Y/N)', max_length=1),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, help_text='생성 일시'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='create_id',
            field=models.CharField(blank=True, help_text='생성자 ID', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='update_date',
            field=models.DateTimeField(auto_now=True, help_text='수정 일시'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='update_id',
            field=models.CharField(blank=True, help_text='수정자 ID', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='use_yn',
            field=models.CharField(default='Y', help_text='사용 여부 (Y/N)', max_length=1),
        ),
        migrations.AlterField(
            model_name='usersolvedproblem',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, help_text='생성 일시'),
        ),
        migrations.AlterField(
            model_name='usersolvedproblem',
            name='create_id',
            field=models.CharField(blank=True, help_text='생성자 ID', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usersolvedproblem',
            name='update_date',
            field=models.DateTimeField(auto_now=True, help_text='수정 일시'),
        ),
        migrations.AlterField(
            model_name='usersolvedproblem',
            name='update_id',
            field=models.CharField(blank=True, help_text='수정자 ID', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usersolvedproblem',
            name='use_yn',
            field=models.CharField(default='Y', help_text='사용 여부 (Y/N)', max_length=1),
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_id', models.CharField(blank=True, help_text='생성자 ID', max_length=50, null=True)),
                ('update_id', models.CharField(blank=True, help_text='수정자 ID', max_length=50, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, help_text='생성 일시')),
                ('update_date', models.DateTimeField(auto_now=True, help_text='수정 일시')),
                ('use_yn', models.CharField(default='Y', help_text='사용 여부 (Y/N)', max_length=1)),
                ('slot_states', models.JSONField(default=dict)),
                ('interview_plan', models.JSONField(default=dict)),
                ('status', models.CharField(default='in_progress', max_length=20)),
                ('current_slot', models.CharField(default='', max_length=50)),
                ('current_turn', models.IntegerField(default=0)),
                ('max_turns', models.IntegerField(default=20)),
                ('just_moved_slot', models.BooleanField(default=False)),
                ('question_history', models.JSONField(default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to='core.userprofile')),
            ],
            options={
                'db_table': 'gym_interview_session',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_id', models.CharField(blank=True, help_text='생성자 ID', max_length=50, null=True)),
                ('update_id', models.CharField(blank=True, help_text='수정자 ID', max_length=50, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, help_text='생성 일시')),
                ('update_date', models.DateTimeField(auto_now=True, help_text='수정 일시')),
                ('use_yn', models.CharField(default='Y', help_text='사용 여부 (Y/N)', max_length=1)),
                ('slot_summary', models.JSONField(default=dict)),
                ('overall_summary', models.TextField()),
                ('top_strengths', models.JSONField(default=list)),
                ('top_improvements', models.JSONField(default=list)),
                ('recommendation', models.TextField(blank=True, default='')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='core.interviewsession')),
            ],
            options={
                'db_table': 'gym_interview_feedback',
            },
        ),
        migrations.CreateModel(
            name='InterviewTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_id', models.CharField(blank=True, help_text='생성자 ID', max_length=50, null=True)),
                ('update_id', models.CharField(blank=True, help_text='수정자 ID', max_length=50, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, help_text='생성 일시')),
                ('update_date', models.DateTimeField(auto_now=True, help_text='수정 일시')),
                ('use_yn', models.CharField(default='Y', help_text='사용 여부 (Y/N)', max_length=1)),
                ('turn_number', models.IntegerField()),
                ('slot', models.CharField(max_length=50)),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True, default='')),
                ('evidence_map', models.JSONField(default=dict)),
                ('slot_status_before', models.CharField(default='UNKNOWN', max_length=20)),
                ('slot_status_after', models.CharField(default='UNKNOWN', max_length=20)),
                ('engine_action', models.CharField(default='', max_length=30)),
                ('intent', models.CharField(default='', max_length=100)),
                ('coach_feedback', models.TextField(blank=True, default='')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='core.interviewsession')),
            ],
            options={
                'db_table': 'gym_interview_turn',
                'ordering': ['turn_number'],
            },
        ),
        migrations.CreateModel(
            name='SavedJobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_id', models.CharField(blank=True, help_text='생성자 ID', max_length=50, null=True)),
                ('update_id', models.CharField(blank=True, help_text='수정자 ID', max_length=50, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, help_text='생성 일시')),
                ('update_date', models.DateTimeField(auto_now=True, help_text='수정 일시')),
                ('use_yn', models.CharField(default='Y', help_text='사용 여부 (Y/N)', max_length=1)),
                ('company_name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('job_responsibilities', models.TextField(blank=True, default='')),
                ('required_qualifications', models.TextField(blank=True, default='')),
                ('preferred_qualifications', models.TextField(blank=True, default='')),
                ('required_skills', models.JSONField(default=list)),
                ('preferred_skills', models.JSONField(default=list)),
                ('experience_range', models.CharField(blank=True, default='', max_length=50)),
                ('deadline', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.CharField(max_length=20)),
                ('source_url', models.URLField(blank=True, default='', max_length=500)),
                ('raw_text', models.TextField(blank=True, default='')),
                ('parsed_data', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_job_postings', to='core.userprofile')),
            ],
            options={
                'db_table': 'gym_saved_job_posting',
                'ordering': ['-create_date'],
            },
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='job_posting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_sessions', to='core.savedjobposting'),
        ),
        migrations.AddConstraint(
            model_name='savedjobposting',
            constraint=models.UniqueConstraint(condition=models.Q(('source_url', ''), _negated=True), fields=('user', 'source_url'), name='unique_user_source_url'),
        ),
    ]
