# Generated by Django 6.0.2 on 2026-02-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_interviewfeedback_vision_analysis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewturn',
            name='coach_feedback',
        ),
        migrations.AlterField(
            model_name='interviewfeedback',
            name='overall_summary',
            field=models.TextField(help_text='전체 면접 총평'),
        ),
        migrations.AlterField(
            model_name='interviewfeedback',
            name='recommendation',
            field=models.TextField(blank=True, default='', help_text='향후 면접 준비를 위한 조언/추천 사항'),
        ),
        migrations.AlterField(
            model_name='interviewfeedback',
            name='slot_summary',
            field=models.JSONField(default=dict, help_text='\n    역량 슬롯별 최종 상태 요약\n    구조 예시:\n    {\n      "collaboration": {\n        "final_status": "CLEAR",\n        "confirmed_evidence": ["role", "action", "result"],\n        "missing_evidence": ["reflection"],\n        "summary": "협업 과정에서의 역할과 결과가 명확히 제시됨..."\n      }\n    }\n    '),
        ),
        migrations.AlterField(
            model_name='interviewfeedback',
            name='top_improvements',
            field=models.JSONField(default=list, help_text='주요 개선점 목록 (JSON 배열)'),
        ),
        migrations.AlterField(
            model_name='interviewfeedback',
            name='top_strengths',
            field=models.JSONField(default=list, help_text='주요 강점 목록 (JSON 배열)'),
        ),
        migrations.AlterField(
            model_name='interviewfeedback',
            name='vision_analysis',
            field=models.JSONField(blank=True, default=None, help_text='비전 분석 데이터 (표정, 시선 처리 등)', null=True),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='current_slot',
            field=models.CharField(default='', help_text='현재 진행 중인 역량 평가 슬롯', max_length=50),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='current_turn',
            field=models.IntegerField(default=0, help_text='현재 진행된 턴(질문/답변) 횟수'),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='interview_plan',
            field=models.JSONField(default=dict, help_text='초기 생성된 면접 계획 데이터'),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='just_moved_slot',
            field=models.BooleanField(default=False, help_text='방금 다른 슬롯으로 넘어갔는지 여부 (자연스러운 브릿지 멘트 생성에 활용)'),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='max_turns',
            field=models.IntegerField(default=20, help_text='해당 세션의 최대 허용 턴 수'),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='question_history',
            field=models.JSONField(default=list, help_text='\n    이전 질문 기록 배열.\n    예: [{"slot": "collaboration", "intent": "행동 회상 유도", "turn": 1}, ...]\n    '),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='slot_states',
            field=models.JSONField(default=dict, help_text='\n    역량 슬롯별 증거 수집 현황 (예: collaboration, leadership 등)\n    구조 예시:\n    {\n      "collaboration": {\n        "status": "PARTIAL", // UNKNOWN, PARTIAL, CLEAR 등\n        "evidence": {"role": true, "action": true, "result": false},\n        "confirmed_required": ["role", "action"],\n        "missing_required": ["result"],\n        "attempt_count": 1,\n        "required": ["role", "action", "result"]\n      }\n    }\n    '),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='status',
            field=models.CharField(default='in_progress', help_text="면접 상태: 'in_progress', 'completed', 'abandoned'", max_length=20),
        ),
        migrations.AlterField(
            model_name='interviewturn',
            name='answer',
            field=models.TextField(blank=True, default='', help_text='사용자(면접자)의 답변'),
        ),
        migrations.AlterField(
            model_name='interviewturn',
            name='engine_action',
            field=models.CharField(default='', help_text="엔진의 다음 행동 결정: 'continue'(계속 질문), 'move_slot'(다음 역량으로 이동), 'finish'(면접 종료)", max_length=30),
        ),
        migrations.AlterField(
            model_name='interviewturn',
            name='evidence_map',
            field=models.JSONField(default=dict, help_text='답변에서 추출된 증거 맵'),
        ),
        migrations.AlterField(
            model_name='interviewturn',
            name='intent',
            field=models.CharField(default='', help_text="다음 질문의 의도 (예: 누락된 '결과' 증거 요구)", max_length=100),
        ),
        migrations.AlterField(
            model_name='interviewturn',
            name='question',
            field=models.TextField(help_text='면접관(AI)의 질문'),
        ),
        migrations.AlterField(
            model_name='interviewturn',
            name='slot',
            field=models.CharField(help_text='이 턴에서 평가 중인 역량 슬롯', max_length=50),
        ),
        migrations.AlterField(
            model_name='interviewturn',
            name='slot_status_after',
            field=models.CharField(default='UNKNOWN', help_text='답변 후 업데이트된 슬롯 상태', max_length=20),
        ),
        migrations.AlterField(
            model_name='interviewturn',
            name='slot_status_before',
            field=models.CharField(default='UNKNOWN', help_text='답변 전 슬롯 상태', max_length=20),
        ),
        migrations.AlterField(
            model_name='interviewturn',
            name='turn_number',
            field=models.IntegerField(help_text='세션 내 턴의 순번'),
        ),
        migrations.AlterField(
            model_name='savedjobposting',
            name='company_name',
            field=models.CharField(help_text='기업명', max_length=200),
        ),
        migrations.AlterField(
            model_name='savedjobposting',
            name='deadline',
            field=models.CharField(blank=True, help_text='마감일', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='savedjobposting',
            name='experience_range',
            field=models.CharField(blank=True, default='', help_text='요구 경력 (예: 신입, 1~3년)', max_length=50),
        ),
        migrations.AlterField(
            model_name='savedjobposting',
            name='job_responsibilities',
            field=models.TextField(blank=True, default='', help_text='주요 업무 내용'),
        ),
        migrations.AlterField(
            model_name='savedjobposting',
            name='parsed_data',
            field=models.JSONField(default=dict, help_text='기타 파싱된 세부 정보 (JSON 구조)'),
        ),
        migrations.AlterField(
            model_name='savedjobposting',
            name='position',
            field=models.CharField(help_text='지원 직무/포지션', max_length=200),
        ),
        migrations.AlterField(
            model_name='savedjobposting',
            name='preferred_qualifications',
            field=models.TextField(blank=True, default='', help_text='우대 사항 (텍스트)'),
        ),
        migrations.AlterField(
            model_name='savedjobposting',
            name='preferred_skills',
            field=models.JSONField(default=list, help_text='우대 기술 스택 목록 (JSON 배열)'),
        ),
        migrations.AlterField(
            model_name='savedjobposting',
            name='raw_text',
            field=models.TextField(blank=True, default='', help_text='파싱 전 원본 텍스트 데이터'),
        ),
        migrations.AlterField(
            model_name='savedjobposting',
            name='required_qualifications',
            field=models.TextField(blank=True, default='', help_text='자격 요건 (텍스트)'),
        ),
        migrations.AlterField(
            model_name='savedjobposting',
            name='required_skills',
            field=models.JSONField(default=list, help_text='필수 기술 스택 목록 (JSON 배열)'),
        ),
        migrations.AlterField(
            model_name='savedjobposting',
            name='source',
            field=models.CharField(help_text="데이터 출처 ('url', 'image', 'text')", max_length=20),
        ),
        migrations.AlterField(
            model_name='savedjobposting',
            name='source_url',
            field=models.URLField(blank=True, default='', help_text='원본 채용공고 URL', max_length=500),
        ),
    ]
