# Generated by Django 6.0.2 on 2026-03-03 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_coachconversation_coachmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBattleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_id', models.CharField(blank=True, help_text='생성자 ID', max_length=50, null=True)),
                ('update_id', models.CharField(blank=True, help_text='수정자 ID', max_length=50, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, help_text='생성 일시')),
                ('update_date', models.DateTimeField(auto_now=True, help_text='수정 일시')),
                ('use_yn', models.CharField(default='Y', help_text='사용 여부 (Y/N)', max_length=1)),
                ('win_count', models.IntegerField(default=0, help_text='승리 횟수')),
                ('draw_count', models.IntegerField(default=0, help_text='무승부 횟수')),
                ('lose_count', models.IntegerField(default=0, help_text='패배 횟수')),
                ('user', models.OneToOneField(help_text='전적 소유자', on_delete=django.db.models.deletion.CASCADE, related_name='battle_record', to='core.userprofile')),
            ],
            options={
                'verbose_name': '사용자 배틀 전적',
                'verbose_name_plural': '사용자 배틀 전적 목록',
                'db_table': 'gym_user_battle_record',
            },
        ),
    ]
