# Generated by Django 6.0.2 on 2026-03-03 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_userbattlerecord'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userbattlerecord',
            table='gym_wars_battle_record',
        ),
    ]
